### ISSUE TITLE
/dev/stratis may not be a directory

### ISSUE THREAD

**Issue by agrover** [stratis-storage/stratisd#704] opened 2018-01-02 23:25 UTC
As @trgill mentions in #682, somebody could have been shady and created a /dev/stratis that is not a directory, which will cause us to fail.

BTW, setup_devlinks() is going to some trouble to not just remove whatever is there and recreate, because the user could have a shell sitting in /dev/stratis/foo, and having it suddenly be sitting in an unlinked empty directory would be confusing.

I'm not sure if this is worth fixing or not. Can't we come up with infinite ways that a root user could deliberately cause stratisd to fail to work properly?

**Comment by mulkieran** [comment] 2019-12-09 17:03
We can use ```fs::metadata``` to check if the directory we just created is a directory. If not it was already there and was a file.

**Comment by mulkieran** [comment] 2020-06-18 01:15
This is old, but it is related to https://github.com/stratis-storage/project/issues/95.

**Comment by jbaublitz** [comment] 2020-06-22 14:21
@mulkieran Once we lift this into udev, we will no longer have control over that piece of things. What we can do, however, is check at the very beginning of stratisd execution, fail to start, and provide a good error message to let users know exactly what the problem is. Does that sound reasonable to you?

**Comment by mulkieran** [comment] 2020-06-22 14:49
> @mulkieran Once we lift this into udev, we will no longer have control over that piece of things. What we can do, however, is check at the very beginning of stratisd execution, fail to start, and provide a good error message to let users know exactly what the problem is. Does that sound reasonable to you?

Sounds good!

**Comment by mulkieran** [comment] 2020-07-27 15:57
We haven't addressed this yet. An interesting thing would be to find out what happens with current version if this does occur. Reassigning.

**Comment by bgurney-rh** [comment] 2020-07-28 16:53
I set up a test where a blank file is created, via `echo "" > /dev/stratis`.

Then, I ran these commands: `stratis pool create spool1 /dev/vdb2` and `stratis fs create spool1 sfs1`.

I saw this in journalctl:
```
stratis_uuids_t[44733]: Symlink /dev/stratis/spool1/sfs1 created.
systemd-udevd[44728]: dm-5: Failed to create symlink '/dev/stratis/spool1/sfs1.tmp-b253:5' to '../../dm-5': Not a directory
```

However, the file is still there, and the directory in `/dev/stratis` was not created:

```
# ls -l /dev/stratis
-rw-r--r--. 1 root root 1 Jul 28 12:44 /dev/stratis
```

**Comment by mulkieran** [comment] 2020-07-28 17:10
@bgurney-rh : thx

**Comment by mulkieran** [comment] 2020-07-28 17:58
@bgurney-rh: I don't think we should check explicitly for this situation, because it would open the door for us to start considering all sorts of equally unlikely situations. But, what it does make clear is that the message from ```stratis_uuids_to_names.rs``` is overstating the situation in some cases. To close this issue out, please drop the level of the message written on successful completion of the script from INFO to DEBUG and change the wording to something like: ```format!("stratis_uuids_to_names completed without error reporting {} and {}", pool_name, fs_name)``` or something pretty similar.

**Comment by mulkieran** [comment] 2020-08-09 13:22
Resolved by merged PR.

**Closed by mulkieran** 2020-08-09 13:22 UTC
