### ISSUE TITLE
Bug 1635424 - stratis - creating a snapshot with "stratis filesystem snapshot" fails with "xfs_db: command not found" due to PATH issue

### ISSUE THREAD

**Issue by DaveWysochanskiRH** [stratis-storage/stratisd#1251] opened 2018-10-03 13:30 UTC
#!/bin/sh
rm -f /tmp/file[123456].bin
for i in $(seq 1 3); do truncate /tmp/file$i.bin --size=1G; losetup -f /tmp/file$i.bin; done
for i in $(seq 4 6); do truncate /tmp/file$i.bin --size=1G; losetup -f /tmp/file$i.bin; done
stratis pool create pool1 /dev/loop[012]
stratis pool create pool2 /dev/loop[345]
stratis pool list
stratis blockdev list pool1
stratis blockdev list pool2
stratis filesystem list pool1
stratis filesystem list pool2
stratis filesystem create pool1 fs1
stratis filesystem create pool2 fs2
stratis filesystem list pool1
stratis filesystem list pool2
stratis filesystem snapshot pool1 fs1 fs1-snap1

Actual results:
INTERNAL ERROR: Command failed: cmd: "/usr/sbin/xfs_admin" "-U" "2877e0f7-9916-4eff-83cf-ee5c6439cabc" "/dev/dm-14", stdout:  stderr: /usr/sbin/xfs_admin: line 38: xfs_db: command not found

**Comment by mulkieran** [comment] 2018-10-03 15:12
I don't see how the version of stratisd being run can be the just released one, 1.0. If it were, the error would not say ```INTERNAL_ERROR```.

This looks like two bugs to me:

* There is an an xfs problem. It looks like ```xfs_admin``` has developed a dependency on ```xfs_db``` in a recent version. Or it maybe lost that dependency in all the versions we tested on, or something.

* stratis-cli should check the version of stratisd before it runs any commands to verify that it is one that stratis-cli is compatible with, but as far as I know, it doesn't.

**Comment by DaveWysochanskiRH** [comment] 2018-10-03 15:58
> I don't see how the version of stratisd being run can be the just released one, 1.0. If it were, the error would not say `INTERNAL_ERROR`.
> 

It was stratisd-0.5.5-2 but Andy indicated he thought this problem existed upstream as well so I filed the bug.  Sorry I should have tried an upstream version but I didn't have one handy.


> This looks like two bugs to me:
> 
>     * There is an an xfs problem. It looks like `xfs_admin` has developed a dependency on `xfs_db` in a recent version. Or it maybe lost that dependency in all the versions we tested on, or something.
> 
>     * stratis-cli should check the version of stratisd before it runs any commands to verify that it is one that stratis-cli is compatible with, but as far as I know, it doesn't.

Did stratis-cli or stratisd change for the snapshot implmentation to no longer call xfs_admin with the same options?

I don't think xfs_admin has changed recently in regards to its calling xfs_db - it's been this way since rhel7 and is upstream as well.

I just ran the reproducer on f28 with the below RPMs:
stratisd-1.0.0-1.module_2238+17e6a46c.x86_64
stratis-cli-1.0.0-2.fc28.noarch

The test passed on this version so it may be something already fixed?

**Comment by mulkieran** [comment] 2018-10-03 16:12
Thanks for checking. I think you must be correct that it is a path problem. Could you do ```which xfs_db``` for both example, just to check where it happens to have got to? We use Rust standard library to manage shelling out to external apps. So, there may be some change in how the standard library manipulates the PATH variable between the two environments you're running on which is at the root of the problem.

```xfs_admin``` arguments have never changed since the snapshot functionality was implemented, so we can rule that out as the cause.

**Comment by DaveWysochanskiRH** [comment] 2018-10-03 16:20
Both environments show /usr/sbin/xfs_db

**Comment by mulkieran** [comment] 2018-10-03 16:53
It is actually pretty hard to believe that the standard library would fail to correctly copy the environment from the parent process. it is almost easier to believe that it is stratisd's PATH variable that differs between the two environments. Since commit b5289494a9612b1788cd6e118cf1d32fa4a6f866 in May 4, ```xfs_admin``` has always been invoked using an absolute path. So, assuming that the el8 version is no older than that, ```xfs_admin``` invocation would succeed regardless of whether it could be found in the PATH, but then ```xfs_db``` would fail if PATH did not contain ```/usr/sbin```. I think the thing to worry about now is what is stratisd's PATH variable value in each environment. That might get at the root cause.

**Comment by mulkieran** [comment] 2018-10-03 17:11
This is a problem, regardless, though, because stratisd is supposed to be able to be run in an environment where no PATH variable is set.

So, long term, it might make sense to prevail on XFS to "improve" their install process so that ```xfs_db``` is invoked w/ the correct absolute path in their shell script. But XFS may not think that is an improvement for various portability reasons. What we really want is an xfs library of course, so that we don't need to shell out in the first place and this problem would go away.

Short term, and very hacky solution, might be to extend the PATH, whether empty or not, w/ the prefix of the absolute path of the application being invoked when invoking the application. I believe that would mean that when the command is invoked it would be able to find any applications that were in that directory.

So, probably we should file a bug against xfs, unless we are certain that xfs will never be run in these early boot environments, but also the hack suggested above might be a good idea.

**Comment by mulkieran** [comment] 2018-10-03 17:31
Alternative 2: Call ```xfs_db``` directly, and avoid the shell script entirely.

**Comment by mulkieran** [comment] 2018-10-03 17:51
Horrors! The real difference is that in first example, ```DB_OPTS``` was somehow set, so ```xfs_admin``` went into _debugging_ mode. We must always prevent that, which we could do by stripping ```DB_OPTS``` out of the environment when we invoke ```xfs_admin```.

**Comment by DaveWysochanskiRH** [comment] 2018-10-03 19:28
Full disclosure - the original bug I saw I think was the result of a bad / corrupted environment.  I am not sure if you want to change anything due to this.  I am ok closing this bug without making any changes.

I am not sure what the plans are for the xfs_admin command or if it is better to call xfs_db directly for things like a uuid change.  May want to ask on linux-xfs about it.

**Comment by mulkieran** [comment] 2018-10-03 19:38
Thanks for the info. That matches w/ the argment. There might be lots of benefits to invoking ```xfs_db``` directly, though, so I'll wait to see what reviewers say.

**Comment by agrover** [comment] 2018-10-03 22:19
closing, notabug (at least currently)

**Closed by agrover** 2018-10-03 22:19 UTC

**Comment by mulkieran** [comment] 2018-10-09 18:53
This was actually fixed by #1252.
