### ISSUE TITLE
Pool create results in partial and incomplete meta data state when encountering an error

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#767] opened 2018-02-16 14:18 UTC
If you try to create a pool and you encounter an error when creating a filesystem for the meta data, stratis will return an error, but is will then leave the system in a bad state with dm tables setup and only partial meta on the disks.  We need to ensure that if during pool creation, if it fails, that we put the system back in it's previous state.  **Note: Ideally we would place the disks back in the exact same state, but removing any stratis signatures is required.**

``` bash
# bin/stratis pool create somepool /dev/sdb
Execution failed: 4: entity not found
[root@strat stratis-cli]# lsblk
NAME                                                       MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                                                          8:0    0   36G  0 disk 
├─sda1                                                       8:1    0    1G  0 part /boot
├─sda2                                                       8:2    0  3.6G  0 part [SWAP]
└─sda3                                                       8:3    0 31.4G  0 part /
sdb                                                          8:16   0   36G  0 disk 
├─stratis-1-1bbf810902124c9b8f8b13e413bf514c-flex-thinmeta 253:0    0   16M  0 dm   
├─stratis-1-1bbf810902124c9b8f8b13e413bf514c-flex-thindata 253:1    0  768M  0 dm   
└─stratis-1-1bbf810902124c9b8f8b13e413bf514c-flex-mdv      253:2    0   16M  0 dm   
sr0                                                         11:0    1 1024M  0 rom  
# dmsetup ls
stratis-1-1bbf810902124c9b8f8b13e413bf514c-flex-thindata	(253:1)
stratis-1-1bbf810902124c9b8f8b13e413bf514c-flex-thinmeta	(253:0)
stratis-1-1bbf810902124c9b8f8b13e413bf514c-flex-mdv	(253:2)
# bin/stratis pool list
Name    Total Physical Size  Total Physical Used
```

**Comment by agrover** [comment] 2018-05-07 20:26
should be fixed by #922

**Comment by tasleson** [comment] 2018-05-07 20:29
The referenced fix does not address this issue, re-opening.

**Comment by mulkieran** [comment] 2021-12-07 14:28
Closing as duplicate of more contemporary #2864.

**Closed by mulkieran** 2021-12-07 14:28 UTC
