### ISSUE TITLE
Filesystem specified by metadata FilesystemSave could not be setup

### ISSUE THREAD

**Issue by alexminder** [stratis-storage/stratisd#2656] opened 2021-06-17 05:12 UTC
After host reboot one filesystem fail to activate:

```
# stratis daemon version
2.4.2
```

```
[2021-06-17T05:07:16Z WARN  libstratis::engine::strat_engine::thinpool::thinpool] Filesystem specified by metadata FilesystemSave { name: "vm_gentoo_musl_initrd", uuid: FilesystemUuid(cb45bd78-7d2d-485a-bad6-3a21139d7584), thin_id: ThinDevId { value: 42 }, size: Sectors(2147483648), created: 1607790380 } could not be setup, reason: DM(Dm(Invalid, "ThinDev table should have exactly one line, has 0 lines"))
```

**Comment by mulkieran** [comment] 2021-06-17 13:11
@alexminder Thank you for the report.

Can you confirm that you have several filesystems and it is only this one that failed to activate?

The specific error you have encountered seems to indicate that stratisd attempted to load a devicemapper table with 0 lines. By code inspection this is impossible, but we can try to reproduce it using the filesystem specifics in the error.

Have you already tried restarting stratisd and found that the error persisted? Another hypothesis for the root cause of your problem is an error in the devicemapper implementation itself.

**Comment by alexminder** [comment] 2021-06-17 16:59
> Can you confirm that you have several filesystems and it is only this one that failed to activate?
YES

> Have you already tried restarting stratisd and found that the error persisted? 
YES

>  Another hypothesis for the root cause of your problem is an error in the devicemapper implementation itself.
No packages changes has been made recently. With the current devicemapper version FS worked fine until now.

**Comment by mulkieran** [comment] 2021-06-18 19:32
@alexminder Thanks for your responses. This is a very unusual error, and we're certainly interested in getting to the bottom of it. Because of the filename, we're assuming that you're running Gentoo. If that is correct, can you tell us if you compiled you're own kernel and if there were any particular devicemapper related options that you chose? Also, is there any manipulation of the Stratis devicemapper stack that you're aware that you might have done not using Stratis?

**Comment by alexminder** [comment] 2021-06-22 09:05
@mulkieran , 
> we're assuming that you're running Gentoo. If that is correct,

YES

> can you tell us if you compiled you're own kernel and if there were any particular devicemapper related options that you chose?

The kernel I compile myself. 

```
CONFIG_BLK_DEV_DM_BUILTIN=y
# CONFIG_DM_DEBUG is not set
CONFIG_DM_BUFIO=y
# CONFIG_DM_DEBUG_BLOCK_MANAGER_LOCKING is not set
CONFIG_DM_BIO_PRISON=y
CONFIG_DM_PERSISTENT_DATA=y
CONFIG_DM_CRYPT=y
CONFIG_DM_SNAPSHOT=y
CONFIG_DM_THIN_PROVISIONING=y
CONFIG_DM_CACHE=y
CONFIG_DM_CACHE_SMQ=y
# CONFIG_DM_WRITECACHE is not set
# CONFIG_DM_ERA is not set
# CONFIG_DM_CLONE is not set
# CONFIG_DM_MIRROR is not set
# CONFIG_DM_RAID is not set
# CONFIG_DM_ZERO is not set
# CONFIG_DM_MULTIPATH is not set
# CONFIG_DM_DELAY is not set
# CONFIG_DM_DUST is not set
CONFIG_DM_INIT=y
CONFIG_DM_UEVENT=y
# CONFIG_DM_FLAKEY is not set
# CONFIG_DM_VERITY is not set
# CONFIG_DM_SWITCH is not set
# CONFIG_DM_LOG_WRITES is not set
CONFIG_DM_INTEGRITY=y
# CONFIG_DM_ZONED is not set
```

> Also, is there any manipulation of the Stratis devicemapper stack that you're aware that you might have done not using Stratis?

NO

I have found the issue happens with old stratisd in initramfs (version 2.1) and latest stratisd in main system. After each reboot random filesystem fail to activate if metadata was update (remove/create fs). 
After updating initramfs stratisd-min all the filesystems activated success.

**Comment by mulkieran** [comment] 2021-06-22 12:52
Could you be entirely specific about what you mean here:

"After updating initramfs stratisd-min all the filesystems activated success." ?

1. As I understand it, you installed stratisd-min. How did you do that precisely? You had not done this before?
2. You rebuilt the initramfs which now included support for Stratis?
3. You rebooted, and this time all the filesystems came up?

Thanks again for your help.

**Comment by alexminder** [comment] 2021-06-23 11:13
1. Previous initramfs image have `stratisd` 2.1 (from dracut staratis module from dracut repo before it was moved to stratisd repo). Now I rebuild initramfs with `stratisd-min` 2.4 with dracut module from stratisd repo.
2. Stratis support in initramfs was before and now, because I have rootfs on stratis.
3. Yes

**Comment by mulkieran** [comment] 2021-09-17 16:43
@alexminder I am more and more confident that this bug is a duplicate of the bug here: https://github.com/stratis-storage/stratisd/issues/2749. The manifestation is different. However, it seems likely that the cause is the same. The problem is that there is a point where stratisd-min is running and systemd brings it down and stratisd comes up. Previously systemd sent a kill signal to stratisd-min and all its child processes to coordinate this. What this meant was that a child process might be killed before stratisd-min was killed. stratisd-min would continue, dealing with the error, but at some time, it would handle the kill signal and also shut down, while stratisd would come up. In some cases, stratisd would encounter an inconsistent devicemapper device state as a result.

The fix is here: https://github.com/stratis-storage/stratisd/pull/2754. You may wish to edit the systemd service files on your own machine in the same way.

I'll close this as a duplicate of https://github.com/stratis-storage/stratisd/issues/2749, as that seems the most likely explanation.

**Closed by mulkieran** 2021-09-17 16:43 UTC
