### ISSUE TITLE
Block devices with meta data opened and read too many times

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#661] opened 2017-11-20 22:18 UTC
If you do an `strace` of stratisd starting up you will see that for every block device that has stratis meta data on it we appear to open/read/close ~5 times.  It would be beneficial, especially in larger configurations to minimize the number of times we read data off the disk to, ideally reading it up only once.

excerpt for `/dev/loop1`
```
openat(AT_FDCWD, "/dev/loop1", O_RDONLY|O_CLOEXEC) = 5
ioctl(5, FIOCLEX)                       = 0
lseek(5, 0, SEEK_SET)                   = 0
read(5, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 8192) = 8192
close(5) 
...
openat(AT_FDCWD, "/dev/loop1", O_RDONLY|O_CLOEXEC) = 5
ioctl(5, FIOCLEX)                       = 0
lseek(5, 0, SEEK_SET)                   = 0
read(5, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 8192) = 8192
close(5)
...
openat(AT_FDCWD, "/dev/loop1", O_RDONLY|O_CLOEXEC) = 4
ioctl(4, FIOCLEX)                       = 0
lseek(4, 0, SEEK_SET)                   = 0
read(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 8192) = 8192
lseek(4, 8192, SEEK_SET)                = 8192
read(4, "s\343C\36^\254\312\16\371\1\0\0\0\0\0\0\305\31\23Z\0\0\0\0\227\3000,\0\0\0\0", 32) = 32
lseek(4, 268288, SEEK_SET)              = 268288
read(4, "i\307\311\367\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
close(4) 
...
openat(AT_FDCWD, "/dev/loop1", O_RDONLY|O_CLOEXEC) = 4
ioctl(4, FIOCLEX)                       = 0
lseek(4, 8224, SEEK_SET)                = 8224
read(4, "{\"name\":\"testpool1\",\"block_devs\""..., 505) = 505
close(4)
...
openat(AT_FDCWD, "/dev/loop1", O_RDONLY|O_CLOEXEC) = 4
ioctl(4, FIOCLEX)                       = 0
lseek(4, 0, SEEK_SET)                   = 0
read(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 8192) = 8192
lseek(4, 8192, SEEK_SET)                = 8192
read(4, "s\343C\36^\254\312\16\371\1\0\0\0\0\0\0\305\31\23Z\0\0\0\0\227\3000,\0\0\0\0", 32) = 32
lseek(4, 268288, SEEK_SET)              = 268288
read(4, "i\307\311\367\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 32) = 32
close(4)               

```

**Comment by mulkieran** [comment] 2017-11-20 22:29
Related: #486. If we disperse the functions, we can establish more precise post-condtions, and somehow read the data a bit less often.

**Comment by mulkieran** [comment] 2017-12-18 15:14
Closing this, since #486 was intended to address this problem, among others.

**Closed by mulkieran** 2017-12-18 15:14 UTC
Labels: enhancement
