### ISSUE TITLE
udev and low water mark detection in stratisd

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/stratisd#1706] opened 2019-11-15 21:16 UTC
@waltdisgrace did some research into low water mark events from the kernel for thin pools in device mapper. So far we know that the kernel will trigger a udev event when the thin pool low water mark is reached. We need to look into how to distinguish this low water mark signal from any other change in the thin pool. Currently there are some questions on how to do this. I'm going to take a look at the messages sent back by netlink to udev to see if there's a way we can determine this in its raw form and move up to udev to see if there's a way to determine it there. I'm also going to take a look at the current code for detecting low water marks and see if that provides any insight.

**Comment by jbaublitz** [comment] 2019-11-18 14:43
I talked with @mulkieran about this and we may need to look into the thinpool implementation more before proceeding.

**Comment by mulkieran** [comment] 2022-03-16 00:01
We are in process of working on this, closing as duplicate of #2814

**Closed** 2022-03-16 00:01 UTC
