### ISSUE TITLE
stratisd logs error and exits intermittently when running script

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#2864] opened 2021-12-02 17:22 UTC
When I run the following script:

```bash
#!/bin/bash

POOLNAME="wtw"
./stratis pool create "$POOLNAME" /dev/sdb /dev/sdc || exit 1
./stratis fs create "$POOLNAME" testfs0 || exit 1
./stratis fs destroy "$POOLNAME" testfs0 || exit 1
./stratis fs create "$POOLNAME" testfs0 || exit 1
./stratis fs rename "$POOLNAME" testfs0 testfs0_renamed || exit 1
./stratis pool rename "$POOLNAME" the_pool || exit 1

POOLNAME="the_pool"
./stratis pool || exit 1
./stratis pool add-data "$POOLNAME" /dev/sdd || exit 1
./stratis fs destroy "$POOLNAME" testfs0_renamed || exit 1
./stratis pool destroy "$POOLNAME" || exit 1

./stratis pool create "$POOLNAME" /dev/sdb /dev/sdc || exit 1
./stratis pool add-data "$POOLNAME" /dev/sdd || exit 1
./stratis pool destroy "$POOLNAME" || exit 1
./stratis pool create "$POOLNAME" /dev/sdb /dev/sdc || exit 1
./stratis pool add-data "$POOLNAME" /dev/sdd || exit 1
./stratis pool destroy "$POOLNAME" || exit 1


```
Stratisd ends up encountering this error

journal entry
```json
{
        "_SELINUX_CONTEXT" : "system_u:system_r:stratisd_t:s0",
        "_BOOT_ID" : "913381531ce746e9b7b42003dfebe3e9",
        "_UID" : "0",
        "_CAP_EFFECTIVE" : "1ffffffffff",
        "_TRANSPORT" : "stdout",
        "__REALTIME_TIMESTAMP" : "1638464872545408",
        "_STREAM_ID" : "9fd269934e934a109b18ee3f4d73b303",
        "_EXE" : "/usr/libexec/stratisd3",
        "_COMM" : "stratisd",
        "_SYSTEMD_CGROUP" : "/system.slice/stratisd.service",
        "__MONOTONIC_TIMESTAMP" : "5485517875",
        "PRIORITY" : "6",
        "_HOSTNAME" : "f35",
        "_MACHINE_ID" : "24cb3e10d7ad435ea0c0ee8f887a5222",
        "SYSLOG_FACILITY" : "3",
        "_SYSTEMD_SLICE" : "system.slice",
        "_SYSTEMD_INVOCATION_ID" : "89f474be55914b9f96c3f834ff8ee4d3",
        "_PID" : "694",
        "MESSAGE" : "The following errors were reported while handling devicemapper eventing; DM error: DM Core error: low-level ioctl error due to nix error; header result: Some(DeviceInfo { version: Version { major: 4, minor: 45, patch: 0 }, data_size: 16384, data_start: 312, target_count: 0, open_count: 0, flags: DM_SUSPEND | DM_NOFLUSH, event_nr: 0, dev: Device { major: 0, minor: 0 }, name: Some(DmNameBuf { inner: \"stratis-1-private-24d25f121753438aaa2cebb2426733b3-thinpool-pool\" }), uuid: None }), error: ENXIO: No such device or address",
        "_CMDLINE" : "/usr/libexec/stratisd --log-level debug",
        "_GID" : "0",
        "__CURSOR" : "s=d0cfa6ec1602412bbbcd101ef0bd62a5;i=8cd3;b=913381531ce746e9b7b42003dfebe3e9;m=146f65c33;t=5d22cd4b47c80;x=312cdd6c83bfebe0",
        "SYSLOG_IDENTIFIER" : "stratisd",
        "_SYSTEMD_UNIT" : "stratisd.service"
}
```

which causes the daemon to exit and leaves the dm tables in a state where they cannot be removed as some tables are in use.  I believe this is due to the mdv still being mounted.

```bash
# lsblk
NAME                                                                    MAJ:MIN RM  SIZE RO TYPE    MOUNTPOINTS
sda                                                                       8:0    0   80G  0 disk    
├─sda1                                                                    8:1    0    1G  0 part    /boot
├─sda2                                                                    8:2    0 53.1G  0 part    /
└─sda3                                                                    8:3    0 25.9G  0 part    /home
sdb                                                                       8:16   0    1G  0 disk    
└─stratis-1-private-24d25f121753438aaa2cebb2426733b3-physical-originsub 253:0    0    2T  0 stratis 
  └─stratis-1-private-24d25f121753438aaa2cebb2426733b3-flex-mdv         253:3    0   16M  0 stratis /run/stratisd/.mdv-24d25f121753438aaa2cebb2426733b3
sdc                                                                       8:32   0    1G  0 disk    
└─stratis-1-private-24d25f121753438aaa2cebb2426733b3-physical-originsub 253:0    0    2T  0 stratis 
  └─stratis-1-private-24d25f121753438aaa2cebb2426733b3-flex-mdv         253:3    0   16M  0 stratis /run/stratisd/.mdv-24d25f121753438aaa2cebb2426733b3
sdd                                                                       8:48   0    2T  0 disk    
└─stratis-1-private-24d25f121753438aaa2cebb2426733b3-physical-originsub 253:0    0    2T  0 stratis 
  └─stratis-1-private-24d25f121753438aaa2cebb2426733b3-flex-mdv         253:3    0   16M  0 stratis /run/stratisd/.mdv-24d25f121753438aaa2cebb2426733b3
sde                                                                       8:64   0    2T  0 disk    
sr0                                                                      11:0    1 1024M  0 rom     
zram0                                                                   252:0    0  3.8G  0 disk    [SWAP]
```

Happens about 1 in 5 runs for me on a test VM.

Code is latest with @jbaublitz patch applied for property change https://github.com/stratis-storage/stratisd/pull/2862

**Comment by jbaublitz** [comment] 2021-12-02 17:40
Hi @tasleson! Could you please provide logs from journald confirming that this is related to the MDV? It should record failure to unmount the MDV if that is the cause. I've bumped into similar problems and intend to put up a PR to resolve that if that is the issue.

**Comment by tasleson** [comment] 2021-12-02 17:43
@jbaublitz 

There is an error relating to this.

```bash
# journalctl -r -u stratisd
-- Journal begins at Thu 2021-11-11 09:37:02 CST, ends at Thu 2021-12-02 11:36:46 CST. --
Dec 02 11:07:52 f35 systemd[1]: stratisd.service: Consumed 14.971s CPU time.
Dec 02 11:07:52 f35 systemd[1]: stratisd.service: Failed with result 'exit-code'.
Dec 02 11:07:52 f35 systemd[1]: stratisd.service: Main process exited, code=exited, status=1/FAILURE
Dec 02 11:07:52 f35 stratisd[694]: The following errors were reported while handling devicemapper eventing; DM error: DM Core error: low-level ioctl error due to nix error; header result: Some(DeviceInfo { version: Version { major: 4, minor: >
Dec 02 11:07:52 f35 stratisd[694]: [2021-12-02T17:07:52Z DEBUG stratisd::stratis::run] 30: thread finished
Dec 02 11:07:52 f35 stratisd[694]: [2021-12-02T17:07:52Z DEBUG stratisd::stratis::run] 31: thread finished
Dec 02 11:07:52 f35 stratisd[694]: [2021-12-02T17:07:52Z DEBUG stratisd::stratis::run] 28: thread finished
Dec 02 11:07:52 f35 stratisd[694]: [2021-12-02T17:07:52Z DEBUG stratisd::stratis::run] 29: thread finished
Dec 02 11:07:52 f35 stratisd[694]: [2021-12-02T17:07:52Z DEBUG stratisd::stratis::run] 27: thread finished
Dec 02 11:07:52 f35 stratisd[694]: [2021-12-02T17:07:52Z DEBUG stratisd::stratis::run] 26: thread finished
Dec 02 11:07:52 f35 stratisd[694]: [2021-12-02T17:07:52Z DEBUG stratisd::stratis::run] 25: thread finished
Dec 02 11:07:52 f35 stratisd[694]: [2021-12-02T17:07:52Z ERROR stratisd::stratis::ipc_support::dbus_support] Failed to process D-Bus object path addition or removal: Checking the shutdown signal failed so stratisd can no longer be notified to>
Dec 02 11:07:52 f35 stratisd[694]: [2021-12-02T17:07:52Z ERROR stratisd::stratis::run] The timer thread exited with an error: The following errors were reported while handling devicemapper eventing; DM error: DM Core error: low-level ioctl er>
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z WARN  stratisd::stratis::dm] Failed to process devicemapper event: The following errors were reported while handling devicemapper eventing; DM error: DM Core error: low-level ioctl erro>
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "24d25f12-1753-438a-aa2c-ebb2426733b3", Stratis device >
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "24d25f12-1753-438a-aa2c-ebb2426733b3", Stratis device >
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "24d25f12-1753-438a-aa2c-ebb2426733b3", Stratis device >
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "24d25f12-1753-438a-aa2c-ebb2426733b3", Stratis device >
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z INFO  stratisd::dbus_api::pool::shared] The following devices with UUIDs 6a85f6e3-1ee3-4bea-8fea-feffa10a2f12 were successfully added to a pool
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool data sub-device belonging to pool with uuid 24d25f12-1753-438a-aa2c-ebb2426733b3 by 4286437376 sectors
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool data sub-device belonging to pool 24d25f12-1753-438a-aa2c-ebb2426733b3 by 4286437376 sectors
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool metadata spare sub-device belonging to pool with uuid 24d25f12-1753-438a-aa2c-ebb2426733b3 by 4259840 sectors
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool metadata spare sub-device belonging to pool 24d25f12-1753-438a-aa2c-ebb2426733b3 by 4266360 secto>
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool metadata sub-device belonging to pool with uuid 24d25f12-1753-438a-aa2c-ebb2426733b3 by 4259840 sectors
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool metadata sub-device belonging to pool 24d25f12-1753-438a-aa2c-ebb2426733b3 by 4266360 sectors
Dec 02 11:07:48 f35 stratisd[694]: [2021-12-02T17:07:48Z DEBUG stratisd::engine::strat_engine::backstore::devices] Verifying device using blkid probe: superblock probe: None, number of partitions: None
Dec 02 11:07:47 f35 stratisd[694]: [2021-12-02T17:07:47Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "24d25f12-1753-438a-aa2c-ebb2426733b3", Stratis device >
Dec 02 11:07:47 f35 stratisd[694]: [2021-12-02T17:07:47Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "24d25f12-1753-438a-aa2c-ebb2426733b3", Stratis device >
Dec 02 11:07:47 f35 stratisd[694]: [2021-12-02T17:07:47Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "24d25f12-1753-438a-aa2c-ebb2426733b3", Stratis device >
Dec 02 11:07:47 f35 stratisd[694]: [2021-12-02T17:07:47Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "24d25f12-1753-438a-aa2c-ebb2426733b3", Stratis device >
Dec 02 11:07:47 f35 stratisd[694]: [2021-12-02T17:07:47Z INFO  stratisd::dbus_api::api::manager_3_0::methods] Pool with UUID 24d25f12-1753-438a-aa2c-ebb2426733b3 was created successfully
Dec 02 11:07:47 f35 stratisd[694]: [2021-12-02T17:07:47Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool data sub-device belonging to pool with uuid 24d25f12-1753-438a-aa2c-ebb2426733b3 by 2506752 sectors
Dec 02 11:07:47 f35 stratisd[694]: [2021-12-02T17:07:47Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool data sub-device belonging to pool 24d25f12-1753-438a-aa2c-ebb2426733b3 by 2506752 sectors
Dec 02 11:07:47 f35 stratisd[694]: [2021-12-02T17:07:47Z WARN  stratisd::engine::strat_engine::thinpool::mdv] Could not unmount MDV: EBUSY: Device or resource busy
Dec 02 11:07:47 f35 stratisd[694]: [2021-12-02T17:07:47Z DEBUG stratisd::engine::strat_engine::backstore::devices] Verifying device using blkid probe: superblock probe: None, number of partitions: None
Dec 02 11:07:47 f35 stratisd[694]: [2021-12-02T17:07:47Z DEBUG stratisd::engine::strat_engine::backstore::devices] Verifying device using blkid probe: superblock probe: None, number of partitions: None
Dec 02 11:07:47 f35 stratisd[694]: [2021-12-02T17:07:47Z INFO  stratisd::dbus_api::api::manager_3_0::methods] Pool with UUID 39be7dad-93cb-4a2b-b3fb-424f1b9cd59c was deleted successfully
Dec 02 11:07:46 f35 stratisd[694]: [2021-12-02T17:07:46Z INFO  stratisd::dbus_api::pool::pool_3_0::methods] Filesystems with UUIDs 3780eb34-39ee-427d-8902-93b73e8fa84c were successfully deleted
```

**Comment by jbaublitz** [comment] 2021-12-02 17:56
I will try to reproduce this and see what I find!

**Comment by jbaublitz** [comment] 2021-12-06 19:23
@tasleson I am unable to reproduce this but I think I see the problem. If it is what I think, this is already resolved in the #2814, but that has not been merged yet. I'm happy to put up a PR to resolve it now if you're willing to test it. Would you be willing to do that since you're able to reproduce it?

**Comment by tasleson** [comment] 2021-12-06 19:25
> @tasleson I am unable to reproduce this but I think I see the problem. If it is what I think, this is already resolved in the #2814, but that has not been merged yet. I'm happy to put up a PR to resolve it now if you're willing to test it. Would you be willing to do that since you're able to reproduce it?

Sure

**Comment by jbaublitz** [comment] 2021-12-06 20:22
Great! Please take a look at #2866.

**Comment by tasleson** [comment] 2021-12-06 21:51
> Great! Please take a look at #2866.

Modified script to run in infinite loop.  After 1-2 minutes I'm getting a failure of:

```
./stratis pool destroy the_pool
Execution failed:
stratisd failed to perform the operation that you requested. It returned the following information via the D-Bus: ERROR: low-level ioctl error due to nix error; header result: Some(DeviceInfo { version: Version { major: 4, minor: 45, patch: 0 }, data_size: 16384, data_start: 312, target_count: 0, open_count: 0, flags: (empty), event_nr: 0, dev: Device { major: 0, minor: 0 }, name: Some(DmNameBuf { inner: "stratis-1-private-a2ffefc7b5ab4fb7989ae57181827d1d-flex-mdv" }), uuid: None }), error: EBUSY: Device or resource busy.
```

The daemon doesn't exit like it did previously, but I have to restart the service to get it working again.

I'm running daemon with fixes for: TotalPhysicalUsed, allocated size and this one.  I had to resolve a conflict as the allocated size signal fix conflicts with the total TotalPhysicalUsed fix.

**Comment by tasleson** [comment] 2021-12-06 21:56
Just did another re-create in one iteration:

```
# journalctl -r -u stratisd
-- Journal begins at Thu 2021-11-11 09:37:02 CST, ends at Mon 2021-12-06 15:55:06 CST. --
Dec 06 15:55:06 f35 stratisd[7333]: [2021-12-06T21:55:06Z WARN  stratisd::stratis::timer] Failed to handle timed pool and filesystem checks: The following errors were reported while handling devicemapper eventin>
Dec 06 15:54:56 f35 stratisd[7333]: [2021-12-06T21:54:56Z WARN  stratisd::stratis::timer] Failed to handle timed pool and filesystem checks: The following errors were reported while handling devicemapper eventin>
Dec 06 15:54:46 f35 stratisd[7333]: [2021-12-06T21:54:46Z WARN  stratisd::stratis::timer] Failed to handle timed pool and filesystem checks: The following errors were reported while handling devicemapper eventin>
Dec 06 15:54:36 f35 stratisd[7333]: [2021-12-06T21:54:36Z WARN  stratisd::stratis::timer] Failed to handle timed pool and filesystem checks: The following errors were reported while handling devicemapper eventin>
Dec 06 15:54:26 f35 stratisd[7333]: [2021-12-06T21:54:26Z WARN  stratisd::stratis::timer] Failed to handle timed pool and filesystem checks: The following errors were reported while handling devicemapper eventin>
Dec 06 15:54:16 f35 stratisd[7333]: [2021-12-06T21:54:16Z WARN  stratisd::stratis::timer] Failed to handle timed pool and filesystem checks: The following errors were reported while handling devicemapper eventin>
Dec 06 15:54:06 f35 stratisd[7333]: [2021-12-06T21:54:06Z WARN  stratisd::stratis::timer] Failed to handle timed pool and filesystem checks: The following errors were reported while handling devicemapper eventin>
Dec 06 15:53:56 f35 stratisd[7333]: [2021-12-06T21:53:56Z DEBUG stratisd::stratis::run] 1: thread finished
Dec 06 15:53:56 f35 stratisd[7333]: [2021-12-06T21:53:56Z WARN  stratisd::stratis::timer] Failed to handle timed pool and filesystem checks: The following errors were reported while handling devicemapper eventin>
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z WARN  stratisd::stratis::dm] Failed to process devicemapper event: The following errors were reported while handling devicemapper eventing; DM error: DM >
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "d9ecb3ec-e31c-434a-83e>
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "d9ecb3ec-e31c-434a-83e>
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "d9ecb3ec-e31c-434a-83e>
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "d9ecb3ec-e31c-434a-83e>
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z INFO  stratisd::dbus_api::pool::shared] The following devices with UUIDs b9cf48ef-f59a-4ae9-b56f-d9ddbc6de14e were successfully added to a pool
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool data sub-device belonging to pool with uuid d9ecb3ec-e31c-434a-83e8-5b93905ac>
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool data sub-device belonging to pool d9ecb3ec-e31c-434a-83e8-5b93905>
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool metadata spare sub-device belonging to pool with uuid d9ecb3ec-e31c-434a-83e8>
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool metadata spare sub-device belonging to pool d9ecb3ec-e31c-434a-83>
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool metadata sub-device belonging to pool with uuid d9ecb3ec-e31c-434a-83e8-5b939>
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool metadata sub-device belonging to pool d9ecb3ec-e31c-434a-83e8-5b9>
Dec 06 15:53:46 f35 stratisd[7333]: [2021-12-06T21:53:46Z DEBUG stratisd::engine::strat_engine::backstore::devices] Verifying device using blkid probe: superblock probe: None, number of partitions: None
Dec 06 15:53:45 f35 stratisd[7333]: [2021-12-06T21:53:45Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "d9ecb3ec-e31c-434a-83e>
Dec 06 15:53:45 f35 stratisd[7333]: [2021-12-06T21:53:45Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "d9ecb3ec-e31c-434a-83e>
Dec 06 15:53:45 f35 stratisd[7333]: [2021-12-06T21:53:45Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "d9ecb3ec-e31c-434a-83e>
Dec 06 15:53:45 f35 stratisd[7333]: [2021-12-06T21:53:45Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "d9ecb3ec-e31c-434a-83e>
Dec 06 15:53:45 f35 stratisd[7333]: [2021-12-06T21:53:45Z INFO  stratisd::dbus_api::api::manager_3_0::methods] Pool with UUID d9ecb3ec-e31c-434a-83e8-5b93905ac826 was created successfully
Dec 06 15:53:45 f35 stratisd[7333]: [2021-12-06T21:53:45Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool data sub-device belonging to pool with uuid d9ecb3ec-e31c-434a-83e8-5b93905ac>
Dec 06 15:53:45 f35 stratisd[7333]: [2021-12-06T21:53:45Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool data sub-device belonging to pool d9ecb3ec-e31c-434a-83e8-5b93905>
Dec 06 15:53:45 f35 stratisd[7333]: [2021-12-06T21:53:45Z WARN  stratisd::engine::strat_engine::thinpool::mdv] Could not unmount MDV: EBUSY: Device or resource busy
Dec 06 15:53:45 f35 stratisd[7333]: [2021-12-06T21:53:45Z DEBUG stratisd::engine::strat_engine::backstore::devices] Verifying device using blkid probe: superblock probe: None, number of partitions: None
Dec 06 15:53:45 f35 stratisd[7333]: [2021-12-06T21:53:45Z DEBUG stratisd::engine::strat_engine::backstore::devices] Verifying device using blkid probe: superblock probe: None, number of partitions: None
Dec 06 15:53:44 f35 stratisd[7333]: [2021-12-06T21:53:44Z INFO  stratisd::dbus_api::api::manager_3_0::methods] Pool with UUID 1c819fb4-cd8f-4044-8f13-291434fedb78 was deleted successfully
Dec 06 15:53:44 f35 stratisd[7333]: [2021-12-06T21:53:44Z INFO  stratisd::dbus_api::pool::pool_3_0::methods] Filesystems with UUIDs 08fd77cf-d7a2-41f1-b995-65e1d77a6b11 were successfully deleted
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "1c819fb4-cd8f-4044-8f1>
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "1c819fb4-cd8f-4044-8f1>
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "1c819fb4-cd8f-4044-8f1>
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "1c819fb4-cd8f-4044-8f1>
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z INFO  stratisd::dbus_api::pool::shared] The following devices with UUIDs 4cddaa22-5818-45cb-a8fc-7f250de73520 were successfully added to a pool
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool data sub-device belonging to pool with uuid 1c819fb4-cd8f-4044-8f13-291434fed>
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool data sub-device belonging to pool 1c819fb4-cd8f-4044-8f13-291434f>
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool metadata spare sub-device belonging to pool with uuid 1c819fb4-cd8f-4044-8f13>
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool metadata spare sub-device belonging to pool 1c819fb4-cd8f-4044-8f>
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool metadata sub-device belonging to pool with uuid 1c819fb4-cd8f-4044-8f13-29143>
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool metadata sub-device belonging to pool 1c819fb4-cd8f-4044-8f13-291>
Dec 06 15:53:43 f35 stratisd[7333]: [2021-12-06T21:53:43Z DEBUG stratisd::engine::strat_engine::backstore::devices] Verifying device using blkid probe: superblock probe: None, number of partitions: None
Dec 06 15:53:42 f35 stratisd[7333]: [2021-12-06T21:53:42Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "1c819fb4-cd8f-4044-8f1>
Dec 06 15:53:42 f35 stratisd[7333]: [2021-12-06T21:53:42Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "1c819fb4-cd8f-4044-8f1>
Dec 06 15:53:42 f35 stratisd[7333]: [2021-12-06T21:53:42Z INFO  stratisd::dbus_api::pool::pool_3_0::methods] Pool with UUID 1c819fb4-cd8f-4044-8f13-291434fedb78 was successfully renamed
Dec 06 15:53:42 f35 stratisd[7333]: [2021-12-06T21:53:42Z INFO  stratisd::dbus_api::filesystem::filesystem_3_0::methods] Filesystem with UUID 08fd77cf-d7a2-41f1-b995-65e1d77a6b11 was successfully renamed
Dec 06 15:53:41 f35 stratisd[7333]: [2021-12-06T21:53:41Z INFO  stratisd::dbus_api::pool::pool_3_0::methods] The following filesystems name: testfs0, UUID: 08fd77cf-d7a2-41f1-b995-65e1d77a6b11, size: 2147483648 >
Dec 06 15:53:40 f35 stratisd[7333]: [2021-12-06T21:53:40Z INFO  stratisd::dbus_api::pool::pool_3_0::methods] Filesystems with UUIDs 5d7c55c5-55a2-4737-83fb-62df407268db were successfully deleted
Dec 06 15:53:40 f35 stratisd[7333]: [2021-12-06T21:53:40Z INFO  stratisd::dbus_api::pool::pool_3_0::methods] The following filesystems name: testfs0, UUID: 5d7c55c5-55a2-4737-83fb-62df407268db, size: 2147483648 >
Dec 06 15:53:38 f35 stratisd[7333]: [2021-12-06T21:53:38Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "1c819fb4-cd8f-4044-8f1>
Dec 06 15:53:38 f35 stratisd[7333]: [2021-12-06T21:53:38Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "1c819fb4-cd8f-4044-8f1>
Dec 06 15:53:38 f35 stratisd[7333]: [2021-12-06T21:53:38Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "1c819fb4-cd8f-4044-8f1>
Dec 06 15:53:38 f35 stratisd[7333]: [2021-12-06T21:53:38Z DEBUG stratisd::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "1c819fb4-cd8f-4044-8f1>
Dec 06 15:53:38 f35 stratisd[7333]: [2021-12-06T21:53:38Z INFO  stratisd::dbus_api::api::manager_3_0::methods] Pool with UUID 1c819fb4-cd8f-4044-8f13-291434fedb78 was created successfully
Dec 06 15:53:38 f35 stratisd[7333]: [2021-12-06T21:53:38Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Extended thinpool data sub-device belonging to pool with uuid 1c819fb4-cd8f-4044-8f13-291434fed>
Dec 06 15:53:38 f35 stratisd[7333]: [2021-12-06T21:53:38Z INFO  stratisd::engine::strat_engine::thinpool::thinpool] Attempting to extend thinpool data sub-device belonging to pool 1c819fb4-cd8f-4044-8f13-291434f>
Dec 06 15:53:38 f35 stratisd[7333]: [2021-12-06T21:53:38Z DEBUG stratisd::engine::strat_engine::backstore::devices] Verifying device using blkid probe: superblock probe: None, number of partitions: None
Dec 06 15:53:38 f35 stratisd[7333]: [2021-12-06T21:53:38Z DEBUG stratisd::engine::strat_engine::backstore::devices] Verifying device using blkid probe: superblock probe: None, number of partitions: None
Dec 06 15:53:38 f35 stratisd[7333]: [2021-12-06T21:53:38Z DEBUG stratisd::stratis::run] 7: thread started
```

**Comment by jbaublitz** [comment] 2021-12-06 22:01
@tasleson Okay, it looks like the primary problem is solved here which is good. The best way to resolve the issue with `EBUSY` is less straightforward. So far we've taken an approach of retrying a few times in places where `EBUSY` is likely to occur given that there's no real way to prevent this from happening when it is related to timing. My guess is that, now that we've confirmed that the MDV was the cause of the problem, running it in a VM causes the timing to occur in a way where the resource is more likely to trigger `EBUSY` and this is likely why I couldn't reproduce it. We've had the same experience running stratisd in containers.

@mulkieran What are your thoughts here? Are retries in order for the MDV teardown and unmount? That has generally solved the problem so far.

**Comment by mulkieran** [comment] 2022-01-29 02:14
I think we've fixed all the signals related bugs, and are in a position to continue monitoring their correctness, closing.

**Comment by mulkieran** [comment] 2022-01-29 02:17
The only extractable left here is possibly retrying on failure to mount/unmount mdv. We can take this off any board, for now.

**Comment by mulkieran** [comment] 2022-01-29 02:21
Closing for #2916.

**Closed by mulkieran** 2022-01-29 02:21 UTC
