### ISSUE TITLE
Incorrect error message when unable to create FS

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratisd#1141] opened 2018-08-31 02:24 UTC
If you exhaust the pool when trying to create a FS you get:

```bash
# bin/stratis filesystem create raided fs3
Execution failure caused by:
INTERNAL ERROR: Command failed: cmd: "/usr/sbin/mkfs.xfs" "-f" "-q" "/dev/dm-17" "-m" "uuid=cc37f37d-3aa5-4d6d-8aeb-4f79af486eec", stdout:  stderr: mkfs.xfs: libxfs_device_zero write failed: No space left on device
```
Listing this as an `INTERNAL ERROR` seems incorrect considering that we ran out of space.

**Comment by agrover** [comment] 2018-09-18 18:58
duplicate of #1181 and #534, closing.

**Closed by agrover** 2018-09-18 18:58 UTC
