### ISSUE TITLE
Stratis filesystem more filesystems on the device error

### ISSUE THREAD

**Issue by devopstales** [stratis-storage/stratisd#1788] opened 2020-01-18 11:05 UTC
I created a separate stratis file-system for my virtualbox disks. I created tree vmdk for a vm in the root of the mounted stratis fs. In the vm I create a zfs pool from that tree disks. After the reboot of my Fedore 31 host can't mount he stratis fs (for the virtualbox) by UUID. 

I tested the device of this stratis fs and get this result:
```
blkid -p /dev/mapper/stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19
blkid: /dev/mapper/stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19: ambivalent result (probably more filesystems on the device, use wipefs(8) to see more details)
```

So what other filesystems?:
```
wipefs /dev/mapper/stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19
DEVICE                                                                              OFFSET  TYPE       UUID                                 LABEL
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x0     xfs        0262354f-ef64-4d28-85b6-46c6676ffd19 
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x3f000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x3e000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x3c000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x3b000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x36000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x35000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x27000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x26000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x24000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x23000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x7c000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x7b000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x76000 zfs_member                                      
stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 0x75000 zfs_member
```

Somehow the zfs membership is written into the stratis fs. How? If the vmdk is not in the root of the stratis fs but in a folder, there is no problem.

My environment:
OS: Fedora 31
Stratis:
```
yum list installed | grep stratis
stratis-cli.x86_64                                 1.0.4-1.module_f31+6320+bf3c8975       @fedora-modular                             
stratisd.x86_64                                    1.0.5-1.module_f31+6320+bf3c8975       @fedora-modular
```

**Comment by mulkieran** [comment] 2020-01-22 15:26
Hi! You're running those blkid and wipefs commands all on the host system?

**Comment by devopstales** [comment] 2020-01-26 14:16
Yes this is on my host system.

**Comment by drckeefe** [comment] 2020-02-03 21:00
@devopstales Thank you for providing this feedback.  This seems strange.  From the information you provided, my guess is that a stratis filesystem was created, then you mounted the filesystem

# mount /stratis/[pool name]/[filesystem name] /[mount path]

Once the filesystem was mounted, within virtualbox you created a disk for a new VM.  The disk path was the mount path for stratis' filesystem.   This should create vmdk file with in the filesystem
that should not be exposed to the host operating system, and therefore, not show up in wipefs.

If the stratis filesystem was not mounted and virtual box was told to used the stratis thin device directly, then maybe we could see these issues?  

If you provided some further information to help me understand this setup, I believe I could be of more assistance.  

Thank you,

**Comment by bgurney-rh** [comment] 2020-02-03 21:27
A potential clue in the source code for blkid:
```
done:
        if (rc == -2) {
                if (ctl->output & OUTPUT_UDEV_LIST)
                        print_udev_ambivalent(pr);
                else
                        warnx(_("%s: ambivalent result (probably more "
                                "filesystems on the device, use wipefs(8) "
                                "to see more details)"),
                                devname);
        }
        close(fd);
```

Note the condition "if (ctl->output & OUTPUT_UDEV_LIST)".  That must be false (but at the top of blkid.c, I see a "deprecated" comment with the description: "udevd links libblkid directly; the 'list' is unnecessary, use lsblk(8)").

So what do you see when you run lsblk on the host?

**Comment by devopstales** [comment] 2020-02-06 20:31
```
NAME                                                                                        MAJ:MIN RM   SIZE RO TYPE    MOUNTPOINT
sda                                                                                           8:0    0 931.5G  0 disk    
└─stratis-1-private-7ac44c27b313400ca1a6a4ca0497d359-physical-originsub                     253:1    0 931.5G  0 stratis 
  ├─stratis-1-private-7ac44c27b313400ca1a6a4ca0497d359-flex-thinmeta                        253:2    0   944M  0 stratis 
  │ └─stratis-1-private-7ac44c27b313400ca1a6a4ca0497d359-thinpool-pool                      253:4    0 930.6G  0 stratis 
  │   ├─stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-7b05ebc52abc451e9f18ba470a684ff0 253:6    0     1T  0 stratis /data
  │   ├─stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 253:7    0     1T  0 stratis /home/admin/VirtualBox VMs
  │   ├─stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-d3e4a5c30fc24064bd7fd70395cecce6 253:8    0     1T  0 stratis /var/data
  │   └─stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-198506756786467a96d94c9a789c55e1 253:9    0     1T  0 stratis /var/lib/docker
  ├─stratis-1-private-7ac44c27b313400ca1a6a4ca0497d359-flex-thindata                        253:3    0 930.6G  0 stratis 
  │ └─stratis-1-private-7ac44c27b313400ca1a6a4ca0497d359-thinpool-pool                      253:4    0 930.6G  0 stratis 
  │   ├─stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-7b05ebc52abc451e9f18ba470a684ff0 253:6    0     1T  0 stratis /data
  │   ├─stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-0262354fef644d2885b646c6676ffd19 253:7    0     1T  0 stratis /home/admin/VirtualBox VMs
  │   ├─stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-d3e4a5c30fc24064bd7fd70395cecce6 253:8    0     1T  0 stratis /var/data
  │   └─stratis-1-7ac44c27b313400ca1a6a4ca0497d359-thin-fs-198506756786467a96d94c9a789c55e1 253:9    0     1T  0 stratis /var/lib/docker
  └─stratis-1-private-7ac44c27b313400ca1a6a4ca0497d359-flex-mdv                             253:5    0    16M  0 stratis
```

**Comment by bgurney-rh** [comment] 2020-02-06 21:00
This seems to suggest something in "/home/admin/VirtualBox VMs" is throwing off the UUID detection.

Under the assumption that it's an XFS filesystem, what could be in that directory that would appear to have "zfs_member" signatures?  Are there any virtual disk files used by VMs that are known to have one or more ZFS pools?

**Comment by devopstales** [comment] 2020-02-08 10:32
@bgurney-rh Yes The disks of my virtual machines is stored in  "/home/admin/VirtualBox VMs" (This is the default behaviour) As i mentioned before I created a zfs pool on some  disk in a vm. I did not understand why is a problem because I did the same thing on a standard lvm xfs file-system, and there was no problem there. On stratis I got this strange situation.

**Comment by drckeefe** [comment] 2020-02-12 16:54
@devopstales I've have a virtualbox setup
Host OS = fedora 30
Virtualbox = 6.1
stratisd, stratiscli = 1.0.5-1, 1.0.4-1
I have one zpool configured and two filesystems with in one VMDK file that is located in the root of the stratis filesystem mount.
Note: The stratis pool was created from a loopback device in this setup.

I don't see this problem.  In my VM i'm using an IDE controller for virtual drives.  Maybe you are using something else?

I upgrade to Fedora 31 to see if this introduces the problem.

**Comment by devopstales** [comment] 2020-02-14 19:51
I used a SATA Controller for my vmdks.

**Comment by drckeefe** [comment] 2020-02-28 14:19
@devopstales I'm not able to reproduce this problem.  I've tried on loop devices initially and wasn't able to reproduce this and then moved the environment to physical storage that would be initialized on boot and mount early hoping that this would reproduce the issue.  I'm just not able to see the zfs devices created in a virtualbox VM, and then identified by the host OS.  I'll keep my test machine around for a few more days if you have any hints on how to reproduce this issue.

**Comment by drckeefe** [comment] 2020-03-03 20:53
Closing issue.  I wasn't able to reproduce this issues.
We can revisit this issue if there is more information in the future. 
Thank you, devopstales for providing this information and replying to questions.

**Closed by drckeefe** 2020-03-03 20:53 UTC
